# Generated by Gemini AI

import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np

def plot_neuron_voltages(file_path="output.csv", spike_threshold=0.0):
    """
    Reads a CSV file where rows represent time steps (in ms) and all columns
    are voltage outputs for different neurons. Generates a raster plot.

    Args:
        file_path (str): The path to the CSV file.
                         Assumes each row is 1ms, and all columns are neuron voltages.
        spike_threshold (float): The voltage value above which a neuron is considered to have spiked.
                                 Defaults to 0.0 to plot all non-zero values.
    """
    if not os.path.exists(file_path):
        print(f"Error: The file '{file_path}' was not found.")
        print("Please make sure 'output.csv' is in the same directory as this script, or provide the full path.")
        return

    try:
        # Read the CSV file into a pandas DataFrame without assuming a time column
        df = pd.read_csv(file_path, header=None) # Assume no header, as all cols are neurons

        # Create the time axis based on the number of rows (each row is 1 ms)
        # Time starts at 0 ms for the first row
        time_column = np.arange(df.shape[0])

        # All columns now represent neuron voltages
        voltage_columns_df = df

        # Ensure there is at least one neuron column
        if voltage_columns_df.shape[1] == 0:
            print("Error: The CSV file must contain at least one column of neuron voltage data.")
            return

        # Create the plot
        plt.figure(figsize=(12, 8)) # Adjust figure size for better readability of many neurons

        # Prepare data for raster plot
        all_spike_data = [] # Will store (neuron_idx, [spike_times]) tuples

        # Iterate through each neuron column by its index (0 to total_neurons-1)
        for neuron_idx in range(voltage_columns_df.shape[1]):
            # Get the voltage series for the current neuron using its integer index
            neuron_voltages = voltage_columns_df.iloc[:, neuron_idx]
            
            # Find time points where voltage exceeds the threshold
            spike_times = time_column[neuron_voltages > spike_threshold].tolist()
            
            if spike_times: # Only add to the list if spikes are detected for this neuron
                all_spike_data.append((neuron_idx, spike_times))

        if not all_spike_data:
            print(f"No spikes detected above the specified threshold ({spike_threshold}).")
            print("Consider lowering the 'spike_threshold' parameter if you expect spikes.")
            plt.title(f'No Spikes Detected (Threshold > {spike_threshold})')
            plt.xlabel('Time (ms)')
            plt.ylabel('Neuron ID')
            plt.show()
            return

        # Separate spike times and their corresponding neuron IDs for plt.eventplot
        event_times_list = [item[1] for item in all_spike_data]
        # Use the actual neuron index as the line offset for correct Y-axis placement
        actual_line_offsets = [item[0] for item in all_spike_data] 

        # Create the raster plot using plt.eventplot
        plt.eventplot(event_times_list, lineoffsets=actual_line_offsets, 
                      linelengths=0.9, # Adjusted linelengths slightly for a more "boxy" look with large linewidth
                      color='black', alpha=0.8,
                      linewidth=10) # Significantly increased linewidth for thicker, box-like lines

        # Determine the total number of neurons from the input CSV columns
        total_neurons = voltage_columns_df.shape[1]

        # Set y-axis labels to correspond to neuron indices (just numbers), showing every 100th label
        display_ticks = []
        display_labels = []
        tick_interval = 100 # Label every 100th neuron

        # Generate ticks and labels for the full range of possible neuron IDs, at the specified interval
        for i in range(0, total_neurons, tick_interval):
            display_ticks.append(i)
            display_labels.append(str(i))
        
        # Add the last neuron's ID if it's not already covered by the interval, and the total_neurons > 0
        if total_neurons > 0 and (total_neurons - 1) % tick_interval != 0:
            if (total_neurons - 1) not in display_ticks: 
                display_ticks.append(total_neurons - 1)
                display_labels.append(str(total_neurons - 1))
            # Sort to ensure ticks and labels are in ascending order
            combined_sorted = sorted(zip(display_ticks, display_labels))
            display_ticks = [t for t, l in combined_sorted]
            display_labels = [l for t, l in combined_sorted]

        plt.yticks(display_ticks, display_labels)
        
        # Add titles and Y-axis label. X-axis label is already "Time (ms)"
        plt.title('Neuron Spiking Raster Plot')
        plt.xlabel('Time (ms)')
        plt.ylabel('Neuron ID') 
        plt.grid(True, axis='x', linestyle='--', alpha=0.7) # Add grid lines for time
        
        # Adjust y-limits based on the total number of neurons in the input file
        plt.ylim(-0.5, total_neurons - 0.5) 

        plt.tight_layout() # Adjust layout to prevent labels from overlapping
        plt.show()

    except Exception as e:
        print(f"An error occurred while processing the CSV file: {e}")
        print("Please ensure the CSV file is correctly formatted with numerical data and no unexpected characters.")

if __name__ == "__main__":
    # Call the function to plot the raster plot
    # You can change the 'spike_threshold' here if your non-zero definition
    # is actually a specific voltage, e.g., plot_neuron_voltages("output.csv", spike_threshold=29.0)
    plot_neuron_voltages("output.csv", spike_threshold=0.0)

